#!/usr/bin/env python
"""Emit the LaTeX tables for the four-way report from raw per-seed JSON.

Same discipline as ``qa_make_report.py``: every number in the report is
generated from the JSON the comparison wrote, so a figure in the PDF cannot
drift from the run that produced it. Nothing is transcribed by hand.

Reads ``data/results/four_way.{baseline,seed,arm-a,arm-b}.json`` and writes
``reports/four_way_tables.tex``.
"""

from __future__ import annotations

import argparse
import itertools
import json
import statistics as st
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

ORDER = [("baseline", r"baseline (no mining)"),
         ("seed", r"\texttt{alpha158\_20} (seed)"),
         ("arm-a", r"Arm A --- RankIC"),
         ("arm-b", r"Arm B --- net-of-cost $\util$")]


def _ms(vals):
    good = [v for v in vals if v is not None and v == v]
    if not good:
        return float("nan"), float("nan")
    return st.mean(good), (st.pstdev(good) if len(good) > 1 else 0.0)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--in-dir", default="data/results")
    ap.add_argument("--out", default="reports/four_way_tables.tex")
    ap.add_argument("--protocol", default="data/results/protocol_mv_tuned.yaml")
    args = ap.parse_args()

    import sys

    sys.path.insert(0, str(ROOT))
    from quantaalpha.eval.protocol import load_protocol

    theta = load_protocol(args.protocol)
    port = theta.portfolio

    blobs, years = {}, None
    for key, _ in ORDER:
        p = Path(args.in_dir) / f"four_way.{key}.json"
        blobs[key] = json.loads(p.read_text())
        ys = [c for c in blobs[key]["metrics"] if c != "full"]
        years = ys if years is None else years

    L = []
    add = L.append
    add(r"% GENERATED by scripts/qa_make_four_way_tex.py -- do not edit.")
    add(rf"\newcommand{{\ThetaHashFW}}{{{theta.hash}}}")
    # Underscores are subscripts in LaTeX text mode; an unescaped
    # "mean_variance" fails to compile rather than rendering oddly. Built
    # outside the f-string because a backslash cannot appear in one (py<3.12).
    construction_tex = port.construction.replace("_", "\\_")
    add(r"\newcommand{\ConstructionFW}{\texttt{" + construction_tex + r"}}")
    add(rf"\newcommand{{\CovFW}}{{{port.covariance}}}")
    add(rf"\newcommand{{\LamFW}}{{{port.risk_aversion:g}}}")
    add(rf"\newcommand{{\CapFW}}{{{port.turnover_cap:g}}}")
    add(rf"\newcommand{{\MaxWFW}}{{{port.max_weight:g}}}")
    add(rf"\newcommand{{\WindowFW}}{{{theta.splits.final_test[0]}--{theta.splits.final_test[1]}}}")

    # ---- headline table -------------------------------------------------
    add(r"\newcommand{\HeadlineTable}{%")
    add(r"\begin{tabular}{lrrrrrr}")
    add(r"\toprule")
    add(r" & \# factors & Rank IC & Net IR & Net ARR & Turnover & Cost (bps) \\")
    add(r"\midrule")
    agg = {}
    for key, label in ORDER:
        m = blobs[key]["metrics"]["full"]
        n = blobs[key]["n_factors"]
        ric, ric_s = _ms(m["rank_ic"])
        ir, ir_s = _ms(m["net_ir"])
        arr, arr_s = _ms(m["net_arr"])
        to, _ = _ms(m["turnover"])
        c, _ = _ms(m["cost_bps"])
        agg[key] = {"rank_ic": (ric, ric_s), "net_ir": (ir, ir_s), "net_arr": (arr, arr_s)}
        add(rf"{label} & {n} & ${ric:+.4f}$ & ${ir:+.4f}$ & ${100*arr:+.2f}\%$ "
            rf"& ${to:.4f}$ & ${c:.2f}$ \\")
    add(r"\bottomrule")
    add(r"\end{tabular}}")

    # ---- per-year tables ------------------------------------------------
    for metric, cmd, spec, scale, suf in (
            ("rank_ic", "YearRankIC", "+.4f", 1.0, ""),
            ("net_arr", "YearNetARR", "+.2f", 100.0, r"\%"),
            ("net_ir", "YearNetIR", "+.4f", 1.0, "")):
        add(rf"\newcommand{{\{cmd}}}{{%")
        add(r"\begin{tabular}{l" + "r" * (len(years) + 1) + r"}")
        add(r"\toprule")
        add(" & " + " & ".join(years) + r" & \textbf{Full} \\")
        add(r"\midrule")
        for key, label in ORDER:
            m = blobs[key]["metrics"]
            cells = []
            for c in years + ["full"]:
                v, _ = _ms(m[c][metric])
                cells.append(rf"${scale*v:{spec}}{suf}$")
            add(f"{label} & " + " & ".join(cells) + r" \\")
        add(r"\bottomrule")
        add(r"\end{tabular}}")

    # ---- resolvability --------------------------------------------------
    add(r"\newcommand{\ResolveTable}{%")
    add(r"\begin{tabular}{llrrl}")
    add(r"\toprule")
    add(r"Comparison & & $\Delta$ Net ARR & $\times$ noise & Verdict \\")
    add(r"\midrule")
    short = {"baseline": "baseline", "seed": r"\texttt{alpha158\_20}",
             "arm-a": "Arm A", "arm-b": "Arm B"}
    for a, b in itertools.combinations([k for k, _ in ORDER], 2):
        (ma, sa), (mb, sb) = agg[a]["net_arr"], agg[b]["net_arr"]
        d = 100 * (mb - ma)
        sd = 100 * max(sa, sb)
        r = abs(d) / sd if sd > 0 else float("inf")
        verdict = "resolvable" if r >= 2 else r"\textbf{not resolvable}"
        add(rf"{short[a]} & vs {short[b]} & ${d:+.2f}$pp & ${r:.1f}\times$ & {verdict} \\")
    add(r"\bottomrule")
    add(r"\end{tabular}}")

    # ---- cost model x construction --------------------------------------
    matrix_dir = Path(args.in_dir)
    variants = [("flat", "topk_dropout"), ("flat", "mean_variance"),
                ("full", "topk_dropout"), ("full", "mean_variance")]
    if all((matrix_dir / f"cost_construction_matrix.{k}.json").exists() for k, _ in ORDER):
        for metric, cmd, spec, scale, suf in (
                ("net_arr", "MatrixNetARR", "+.2f", 100.0, r"\%"),
                ("turnover_book", "MatrixTurnover", ".4f", 1.0, "")):
            add(rf"\newcommand{{\{cmd}}}{{%")
            add(r"\begin{tabular}{lrrrr}")
            add(r"\toprule")
            add(r" & \multicolumn{2}{c}{flat fee} & \multicolumn{2}{c}{full costs} \\")
            add(r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}")
            add(r" & top-$k$ & mean-var & top-$k$ & mean-var \\")
            add(r"\midrule")
            for key, label in ORDER:
                m = json.loads((matrix_dir / f"cost_construction_matrix.{key}.json")
                               .read_text())["metrics"]
                cells = []
                for ck, g in variants:
                    v, _ = _ms(m[f"{ck}/{g}"][metric])
                    cells.append(rf"${scale*v:{spec}}{suf}$")
                add(f"{label} & " + " & ".join(cells) + r" \\")
            add(r"\bottomrule")
            add(r"\end{tabular}}")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out} ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
